version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: uvicorn src.main:app --root-path /api --proxy-headers --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    command: npm start
    depends_on:
      - server
