version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: uvicorn src.main:app --root-path /api --proxy-headers --host 0.0.0.0 --port 8000

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - server

volumes:
  caddy-data:
  caddy-config:
